"""Add is_admin column to user table

Revision ID: 266d91427c65
Revises: 
Create Date: 2024-12-09 16:48:26.937829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '266d91427c65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
